site_name: Família do Sítio

repo_name: "2024.2-T03-CafeDoSitio"
repo_url: https://github.com/mdsreq-fga-unb/2024.2-T03-CafeDoSitio

nav:
  - Início: index.md
  - Visão do Produto e Projeto:
    - Cenário Atual do Cliente e Negócio: sections/2-docPage/1-cenarioAtual.md
    - Solução Proposta: sections/2-docPage/2-solucaoProposta.md
    - Estratégias de Engenharia de Software: sections/2-docPage/3-estrategiasEngSoftware.md
    - Cronograma e Entregas: sections/2-docPage/4-cronogramaEntregas.md
    - Interação entre Equipe e Cliente: sections/2-docPage/5-interacaoEquipeCliente.md
  - Ciclos e Backlog:
    - Visão do Backlog: sections/4-sprints/VisaoGeralBacklog.md
    - Sprint 1:
      - Historico do Backlog: sections/4-sprints/sprint1/HistoricoBacklog.md
      - Reuniões:
        - Kick Off com Stakeholders: sections/4-sprints/sprint1/reuniões/[Stakeholders]04Nov2024.md
        - Planning: sections/4-sprints/sprint1/reuniões/[Equipe]04Nov2024.md
        - Lean Inception pt.1: sections/4-sprints/sprint1/reuniões/[Stakeholders]06Nov2024.md
        - Lean Inception pt.2: sections/4-sprints/sprint1/reuniões/[Stakeholders]07Nov2024.md
        - Lean Inception pt.3: sections/4-sprints/sprint1/reuniões/[Equipe]07Nov2024.md
        - Lean Inception pt.4: sections/4-sprints/sprint1/reuniões/[Equipe]08Nov2024.md
  - Políticas:
    - GCS: sections/3-politicas/gcs.md

theme:
  name: material
  language: pt-BR

  features:
    - content.code.annotate
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.top
    - navigation.tracking

  palette:
    - scheme: default
      primary: 'green'
      accent: 'lime'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
        
    - scheme: slate
      primary: 'green'
      accent: 'lime'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  
  logo: assets/CafeSitioLogo.png
  favicon: assets/CafeSitioLogo.png
  highlightjs: true

extra_css:
  - stylesheets/styles.css