name: Novo Épico
description: Registre um novo Épico (Agrupamento de Funcionallidades) no projeto da Família do Sítio.
title: "[EP<Código da US>]: <Título do Épico>"
projects: ["mdsreq-fga-unb/46"]
labels: ["epic"]
body:
  - type: textarea
    id: text-zone1
    attributes:
      label: Descreva este Épico
      description: O que este épico visa construir quanto todas as suas Users Stories forem finalizadas?
    validations:
      required: true
  - type: textarea
    id: text-zone2
    attributes:
      label: Quais são as Users Stories Associadas à este Épico?
      description: Liste, referenciando as US com a hashtag as Users Stories que pertencem à este épico.
      value: |
        - [ ] Épico 1;
        - [ ] Épico 2;
        - [ ] Épico 3.
    validations:
      required: true
  - type: textarea
    id: text-zone3
    attributes:
      label: Detalhes adicionais?
      description: Acrescente informações que possam ser pertinentes para o time.
      placeholder: |
        Escreve ou deixe em branco...
